import NavBar from '@/components/NavBar'
import ProductCard from '@/components/ProductCard'
import { Product } from '@/components/product'
import { GetStaticProps } from 'next'
import Head from 'next/head'

export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch('http://localhost:8080/api/products')
  const products = await response.json()
  return { props: { products }, revalidate: 60 }
}

export default function HomePage({ products }: { products: Product[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar></NavBar>
      <main>
        <ul className='products'>
          {products.map(product => (
            <ProductCard key={product.id} product={product}></ProductCard>
          ))}
        </ul>
      </main>
    </>
  )
}
