import NavBar from '@/components/NavBar'
import { StateContext } from '@/components/StateContext'
import { Product } from '@/components/product'
import Head from 'next/head'
import { useContext } from 'react'

export const getStaticPaths = async () => {
  const response = await fetch('http://localhost:8080/api/products')
  const products = await response.json()
  const paths = products.map((product: Product) => ({
    params: { id: product.id.toString() },
  }))
  return { paths, fallback: false }
}

export const getStaticProps = async ({
  params,
}: {
  params: { id: string }
}) => {
  const response = await fetch(
    `http://localhost:8080/api/products/${params.id}`,
  )
  const product = await response.json()
  return { props: { product } }
}

export default function ProductDetailPage({ product }: { product: Product }) {
  // const { product } = useLoaderData() as { product: Product }
  const { shoppingCart, setShoppingCart } = useContext(StateContext)

  const addToCart = () => {
    const cart = structuredClone(shoppingCart)
    if (cart.some(item => item.id === product.id)) {
      return
    }
    cart.push(product)
    setShoppingCart(cart)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar></NavBar>
      <section id='product-detail-section'>
        <div className='product-slideshow'>
          <div className='slide'>
            <img
              className='product-slideshow-image'
              src='/images/macbook1.jpg'
              alt='Product preview'
            />
          </div>
          <div className='slide'>
            <img
              className='product-slideshow-image'
              src='/images/macbook2.jpg'
              alt='Product preview'
              loading='lazy'
            />
          </div>
        </div>
        <div className='product-details-wrapper'>
          <h1>{product.name}</h1>
          <p>{product.description}</p>
          <p>${Math.round(product.price * 100) / 100}</p>
          <button
            type='submit'
            className='add-to-cart-btn'
            onClick={() => addToCart()}
          >
            Add to cart
          </button>
        </div>
      </section>
    </>
  )
}
